version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1
  snyk: snyk/snyk@2.0.1 

executors:
  docker:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest

jobs:

  build:
    executor: docker
    environment:
      AWS_DEFAULT_REGION: us-east-1
      
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout   
      - run: 
          name: Install Zip & Sudo
          command: apt-get update && apt-get install -y zip sudo make
      - aws-cli/setup:
            role_arn: $role_arn
      - run:
          name: Build
          environment:
            name: sai-test
          command: |
                export SHORT_COMMIT_HASH=$(echo $CIRCLE_SHA1 | cut -c 1-8)
                export COMMIT_EPOCH=$(git show -s --format=%ct $SHORT_COMMIT_HASH)
                export VERSION=$(date -d @$COMMIT_EPOCH +"%F").$SHORT_COMMIT_HASH
                aws codeartifact login --tool dotnet --domain onei3 --domain-owner 615875458684 --repository nuget    
                docker build -t $(name):$(VERSION) .
      - persist_to_workspace:
          root: ~/
          paths:
            - project/    

  snyk_scan:
    executor: docker
    parameters:
      monitor-on-build:
        type: boolean
        default: false
    steps:
      - attach_workspace:
          at: ~/
      - snyk/scan:
          monitor-on-build: << parameters.monitor-on-build >>
          additional-arguments: --prune-repeated-subdependencies --all-projects
          fail-on-issues: false
          organization: $SNYK_ORG
  
  ecr_publish:
    #name: Publish to ECR
    executor: docker
    steps: 
      - attach_workspace:
          at: ~/
      - run:
         command: |
             make publish version=${VERSION}
      
  deploy_lambda:
    executor: docker
    parameters:
      lambda_function_name:
        type: string
        default: none
    steps:
      - aws-cli/setup:
          role_arn: $role_arn
          role_session_name: AWSCLI-Session
      - run:
          name: Deploying new image to lambda function
          command: |
            echo $AWS_ACCOUNT_ID
            aws lambda update-function-code --function-name << parameters.lambda_function_name >> --image-uri 615875458684.dkr.ecr.us-east-1.amazonaws.com/sai-test:$CIRCLE_SHA1 --region us-east-1


workflows:
  
  build:
    jobs:
      - build: 
          context: role_arn
          filters:  
            branches:
              ignore:
                - main
                - master    
      - ecr_publish:
          name: Publish to ECR
          requires:
            - build
          context: role_arn
          filters:  
            branches:
              only:
                - main
                - master 

      - snyk_scan:
          name: Snyk-scan for security issues
          requires:
            - build
          context: snyk   

  # build_and_deploy_lambda:
  #   jobs:
  #     - build:
  #         name: Build and push image to ECR
  #         context: role_arn
  #         push_image: true
  #         filters:  
  #           branches:
  #             only:
  #               - main
  #               - master

  #     - snyk_scan:
  #         name: Snyk-scan for security issues
  #         requires:
  #           - Build and push image to ECR
  #         context: snyk

  #     - hold: 
  #         name: Approve for staging-lambda deployment
  #         type: approval
  #         requires:
  #           - Build and push image to ECR

  #     - deploy_lambda:
  #         name: Deploying into staging-lambda
  #         lambda_function_name : sai-test
  #         context: role_arn
  #         requires:
  #           - Approve for staging-lambda deployment

  #     - hold: 
  #         name: Approve for production-lambda deployment
  #         type: approval
  #         requires:
  #           - Build and push image to ECR

  #     - deploy_lambda:
  #         name: Deploying into production-lambda
  #         lambda_function_name : sai-test
  #         context: role_arn
  #         requires:
  #           - Approve for production-lambda deployment

