version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          role-arn: arn:aws:iam::615875458684:role/gitlab-ci-iceberg-sdk
          dockerfile: Dockerfile
          path: .
          repo: sai-test
          tag: "$CIRCLE_SHA1"
