version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0

jobs:
  build_and_push_image:
    docker:
      - image: cimg/base:stable

    parameters:
        push_image:
          type: boolean
          default: false

    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout 

      - run: |

         SHORT_COMMIT_HASH=$(echo $CIRCLE_SHA1 | cut -c 1-8)
         CURRENT_DATE=$(date +"%Y%m%d")   
         IMAGE_TAG="$SHORT_COMMIT_HASH-$CURRENT_DATE"
    
         echo "Generated Docker image tag: $IMAGE_TAG"
              
      - aws-ecr/build_and_push_image:
          account_id: $AWS_ACCOUNT_ID
          auth:
            - aws-cli/setup:
                role_arn: $role_arn
                role_session_name: ecr
          dockerfile: Dockerfile
          path: .
          repo: sai-test
          region: us-east-1
          tag: "$IMAGE_TAG,latest"
          push_image: << parameters.push_image >>


workflows:
  
  # build:
  #   jobs:
  #     - build_and_push_image:
  #         context: role_arn
  #         push_image: false

  build_and_push_image:
    jobs:
      - build_and_push_image:
          context: role_arn
          push_image: true

